# Generated by Django 4.2 on 2023-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_days',
            field=models.PositiveIntegerField(null=True, verbose_name='Длина подписки(дней)'),
        ),
    ]
