# Generated by Django 4.2 on 2023-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_user_subscription_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_of_subscription',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения подписки'),
        ),
    ]
