# Generated by Django 4.2 on 2023-04-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_restartinterval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestartInterval',
            new_name='RefreshInterval',
        ),
        migrations.CreateModel(
            name='StopWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
