# Generated by Django 4.2 on 2023-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_bitrixaccountdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auth',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
